OCPBUGS-3469: Multi-arch support
operator-framework/java-operator-plugins pull request #114
Opened 2023-03-06 21:19 UTC by oceanc80

Add configurable multi-arch build support

2023-03-06 21:50 UTC, everettraven requested changes
These changes currently don't work when attempting to initialize a project using `operator-sdk init ...`. I left a comment showing the error I received and what I think the solution is.

Another thing I noticed is there is a few commits with multiple contributors and looks like it would re-commit a few already merged commits. I think a `git rebase` (or similar operation) may have gone a bit off the rails as I would have only expected the Makefile template and the testdata to be updated by this PR.

2023-03-06 21:50 UTC, everettraven commented on pkg/quarkus/v1alpha/scaffolds/internal/templates/makefile.go
> +ARCH ?= {{ .Arch }}
One thing to note here is that with the Go templates, to use the notation `{{ .X }}` the field has to exist on the object being used to render the template. When I attempted to run `operator-sdk init ...` with the changes on this branch I received the error:
```
FATA[0000] failed to initialize project: unable to scaffold with "quarkus.javaoperatorsdk.io/v1-alpha": template: *templates.Makefile:5:9: executing "*templates.Makefile" at <.OS>: can't evaluate field OS in type *templates.Makefile 
```

To fix this I think we need to:
1. Update the `Makefile` struct definition:
https://github.com/operator-framework/java-operator-plugins/blob/0eed476d2b7548daf184fb7a836ab8ac8e0dead9/pkg/quarkus/v1alpha/scaffolds/internal/templates/makefile.go#L25-L37
to have those fields.

2. Update the `Makefile.SetTemplateDefaults()` function:
https://github.com/operator-framework/java-operator-plugins/blob/0eed476d2b7548daf184fb7a836ab8ac8e0dead9/pkg/quarkus/v1alpha/scaffolds/internal/templates/makefile.go#L39-L62
to set the default values if they are not specified. I think a good default here would be `OS := linux` && `Arch := amd64`.

2023-03-09 04:09 UTC, laxmikantbpandhare approved these changes
/lgtm

I will try updated tutorial steps on the weekend.

2023-03-09 22:03 UTC, everettraven commented
So I think the changes look good and make sense, but I just can't seem to get an image to actually be built when running `make docker-build`. However, this isn't unique to this PR and also happens when trying to run `make docker-build` on the testdata/quarkus/memcached-quarkus-operator sample on the main branch.

2023-03-21 19:58 UTC, everettraven approved these changes
/lgtm

2023-03-21 20:03 UTC, merged