Unit tests for init.go
operator-framework/java-operator-plugins pull request #24
Opened 2021-07-06 19:35 UTC by VenkatRamaraju

Added unit tests for init.go along with the suite tests for the v1 package.

2021-07-06 19:49 UTC, laxmikantbpandhare approved these changes

2021-07-06 19:50 UTC, VenkatRamaraju commented on pkg/quarkus/v1alpha/init_test.go
> +		// Need clarification on what to set ErrorHandlingNumber as
Some suggestions on what to put as the ErrorHandlingNumber (currently -1) would be helpful.

2021-07-06 19:50 UTC, VenkatRamaraju commented on pkg/quarkus/v1alpha/init_test.go
> +		// Need clarification on what to set Version number as
Here as well - suggestions on what to set as the "default" version number would be helpful.

2021-07-06 22:20 UTC, VenkatRamaraju commented
Also, I did not write a test for the `Scaffold()` function ([here](https://github.com/operator-framework/java-operator-plugins/blob/main/pkg/quarkus/v1alpha/init.go#L119)). It only makes calls to external functions, so wasn't sure if I should trace all of them and write test cases for each one.

If you want me to dig into it and write a test for `Scaffold()` as well, I'll do that. Let me know.

2021-07-08 18:36 UTC, laxmikantbpandhare commented
Everything is working perfect.

```
Running Suite: v1
=================
Random Seed: 1625769325
Will run 16 of 16 specs

••••••••••••••••
Ran 16 of 16 Specs in 0.000 seconds
SUCCESS! -- 16 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 1.138961774s
Test Suite Passed
```

2021-07-08 18:38 UTC, laxmikantbpandhare commented
/lgtm

2021-07-14 03:21 UTC, jmrodri requested changes
Update the test similar to the other PR comments.

2021-07-14 03:21 UTC, jmrodri commented on pkg/quarkus/v1alpha/init_test.go
> +	}
Put in a `BeforeEach` block. that way each test has a fresh version that hasn't been affected by any changes from subsequent test.

2021-07-14 03:21 UTC, jmrodri commented on pkg/quarkus/v1alpha/init_test.go
> +		successInitSubcommand.UpdateMetadata(testCliMetadata, &testSubcommandMetadata)
Should be part of the `It`

2021-07-22 13:51 UTC, jmrodri approved these changes
/lgtm

2021-07-22 13:52 UTC, merged