Unit tests for api.go
operator-framework/java-operator-plugins pull request #27
Opened 2021-07-08 18:14 UTC by VenkatRamaraju

Added unit tests for v1alpha/api.go

**Note:** These tests depend on the `v1_suite_test.go` test suite file from this PR: #24.

2021-07-08 18:40 UTC, laxmikantbpandhare commented
Working fine.
```
Running Suite: V1alpha Suite
============================
Random Seed: 1625769627
Will run 18 of 18 specs

••••••••••••••••••
Ran 18 of 18 Specs in 0.000 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 1.119981223s
Test Suite Passed
```

2021-07-08 18:41 UTC, laxmikantbpandhare approved these changes
/lgtm

2021-07-14 03:17 UTC, jmrodri requested changes
A few changes to the test structure.

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +		})
The `UpdateResource` method call should be in the `It` blocks. OR put it in a `BeforeEach` block.

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +		updateTestResource := resource.Resource{}
I would move these into a `BeforeEach` block. 
```suggestion
    var (
        testAPIOptions     createAPIOptions
        updateTestResource resource.Resource
    )   
    BeforeEach(func() {
        testAPIOptions = &createAPIOptions{
            CRDVersion: "testVersion",
            Namespaced: true,
        }   
        updateTestResource = resource.Resource{}
    })  
```

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +		testAPIOptions.UpdateResource(&updateTestResource)
Make this call inside the `It` blocks. Or you could put all of the expects in a single It. Either way is fine. I'm okay with it being in multiple `Its`.
```suggestion
	It("...", func() {
		testAPIOptions.UpdateResource(&updateTestResource)
		Expect(....)
	})
```

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +			Expect(updateTestResource.API.CRDVersion, testAPIOptions.CRDVersion)
This suggestion applies to all the `Expect`s

```suggestion
			Expect(updateTestResource.API.CRDVersion).To(Equal(testAPIOptions.CRDVersion))
```

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +		testAPISubcommand.BindFlags(flagTest)
Put in the `It`

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +	})
These tests are using a `testApiSubcommand` that you created in another test. You want tests to always have a clean version, they should not depend on what happens in another test. That's why the `BeforeEach` comes in handy.

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +		groupErr := failAPISubcommand.InjectResource(&failResource)
These calls should be included with the `It` blocks. Basically consider the `It` as a specific test and it should include the call and the expectations.

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +		versionErr := failAPISubcommand.InjectResource(&failResource)
This has to be inside the `It` block. Otherwise you are affecting subsequent tests.

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +		kindError := failAPISubcommand.InjectResource(&failResource)
Same comment as above

2021-07-14 03:17 UTC, jmrodri commented on pkg/quarkus/v1alpha/api_test.go
> +		noErr := testAPISubcommand.InjectResource(&testResource)
This too

2021-07-16 02:51 UTC, jmrodri approved these changes
/lgtm

2021-07-16 02:51 UTC, merged