feat: Create a release script for releasing java-operator-plugins
operator-framework/java-operator-plugins pull request #36
Opened 2021-08-28 15:44 UTC by jmrodri

2021-08-28 15:50 UTC, jmrodri commented
### Invalid version specified
```
$ ./release.sh foo
malformed version: "foo"
```

### Not in a release branch
```
$ ./release.sh v0.0.1
branch: "infra-release" is not a release branch, please create a release branch in the form of vX.Y.x
```

### Uncommitted changes
```
$ ./release.sh v0.0.1
directory has uncommitted files
```

### Full release
```
$ ./release.sh v0.0.1
Running tests
Checking for license header...
ok      github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1alpha 0.011s  coverage: 75.0% of statements
?       github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1alpha/scaffolds       [no test files]
ok      github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1alpha/scaffolds/internal/templates    0.006s  coverage: 29.4% of statements
?       github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1alpha/scaffolds/internal/templates/controller [no test files]
?       github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1alpha/scaffolds/internal/templates/model      [no test files]
ok      github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1alpha/scaffolds/internal/templates/util       0.007s  coverage: 100.0% of statements
ok      github.com/operator-framework/java-operator-plugins/pkg/quarkus/v1alpha/util    0.007s  coverage: 100.0% of statements
Creating a new tag for java-operator-plugins version v0.0.1
warning: refname 'v0.0.1' is ambiguous.
object dc02856add27bf54818dfc1bfc0b4efe631e6a10
type commit
tag v0.0.1
tagger jesus m. rodriguez <jesusr@redhat.com> 1630165665 -0400

java-operator-plugins v0.0.1
gpg: Signature made Sat 28 Aug 2021 11:47:45 AM EDT
gpg:                using DSA key BF6F6F18846753754CBB1DDFBC9679ED89ED8983
gpg: Good signature from "Jesus Miguel Rodriguez (jesusr) <jesusr@redhat.com>" [ultimate]
gpg:                 aka "jesus rodriguez (jmrodri) <jmrodri@gmail.com>" [ultimate]

Done forget to:

git push upstream <release-branch>
git push upstream v0.0.1

Also update the release notes in github for this tag.
```

2021-08-28 15:50 UTC, jmrodri commented
Fixes #30

2021-08-28 17:04 UTC, metacosm requested changes

2021-08-28 17:04 UTC, metacosm commented on release.sh
> +echo "Done forget to:"
```suggestion
echo "Don't forget to:"
```

2021-08-28 17:05 UTC, metacosm commented
Looks good to me, though, perhaps it would make sense to investigate using GitHub actions for this at some point?

2021-08-28 21:45 UTC, jmrodri commented
@metacosm fixed the typo (that's what I get for copying code :) and I am not opposed to the github action. The one we have on operator-sdk is a bit more complicated so I didn't want to use that.

2021-08-29 06:05 UTC, metacosm approved these changes

2021-08-30 14:22 UTC, asmacdo approved these changes

2021-08-30 18:23 UTC, laxmikantbpandhare approved these changes

2021-08-30 18:25 UTC, merged